site_name: advent-of-code-python
repo_url: https://github.com/dsiu/advent-of-code-python
site_url: https://dsiu.github.io/advent-of-code-python
site_description: This is a template repository for Python projects that use uv for their dependency management.
site_author: Danny Siu
edit_uri: edit/main/docs/
repo_name: dsiu/advent-of-code-python
copyright: Maintained by <a href="https://dsiu.com">dsiu</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["aoc"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dsiu/advent-of-code-python
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/advent-of-code-python

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
